dist: trusty
language: python
services: docker

jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t webbox --quiet .
      - docker images
    - stage: test
      script: docker run --rm webbox python3 -m unittest tests/test.py
    - script: docker run --rm webbox python3 -m unittest tests/test.py