dist: trusty
language: python
services: docker

jobs:
  include:
    - stage: build docker image and test webbox
      script:
      - docker build -t webbox --quiet .
      - docker images
      - docker run --rm webbox python3 -m unittest tests/test.py